Repository blindsidenetworks/scalelite, pull requests merged in 2021-02, with the labels that each got.

#270 Update sharedvolume-README.md
  sharedvolume-README.md
Labels: v1.0.9

#258 Update scalelite_batch_import.sh
  bigbluebutton/scalelite_batch_import.sh
Labels: in review

#408 SL-56 & SL-61 : Add recording constraints
  README.md
  app/constraints/recording_constraint.rb
  app/controllers/bigbluebutton_api_controller.rb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/routes.rb
  test/controllers/bigbluebutton_api_controller_test.rb
  test/test_helper.rb
Labels: in review, v1.0.9

#261 Scan only BBB servers which are online and enabled in scalelite
  lib/tasks/status.rake
Labels: in review, v1.0.9

#115 Added support for multiple shared secrets.
  README.md
  app/controllers/concerns/api_helper.rb
  config/application.rb
  config/environments/test.rb
  test/test_helper.rb
Labels: in review

#426 SL-67 & SL-68 : Add separate routes for each recording api
  app/constraints/recording_constraint.rb
  app/controllers/bigbluebutton_api_controller.rb
  config/routes.rb
  test/controllers/bigbluebutton_api_controller_test.rb
Labels: in review
