Repository blindsidenetworks/scalelite, pull requests merged in 2021-09, with the labels that each got.

#619 Fix db:migrate task and auto-bootstrap DB in bin/start
  bin/start
  db/migrate/20200131102608_init.rb
Labels: in review

#430 define log level as env
  README.md
  config/environments/production.rb
Labels: v1.3

#578 add load column to rake status table
  lib/tasks/status.rake
Labels: enhancement, needs work, v1.3

#593 SL-183: Fix for Problem joining meeting via Scalelite using POST
  config/routes.rb
  test/controllers/bigbluebutton_api_controller_test.rb
Labels: v1.3
